version: "3.9"

services:
  backend:
    build: ./backend
    container_name: gaze-backend
    environment:
      - NODE_ENV=production
    volumes:
      - ./asddb.sqlite3:/app/../asddb.sqlite3
    ports:
      - "5001:5001"

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: gaze-streamlit
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./asddb.sqlite3:/app/asddb.sqlite3
    ports:
      - "8501:8501"

  frontend:
    build: ./frontend
    container_name: gaze-frontend
    depends_on:
      - backend
      - streamlit
    ports:
      - "8080:80"

networks:
  default:
    name: gaze-net


